# Generated by Django 4.2.3 on 2023-07-26 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skills', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='skill',
            old_name='emage',
            new_name='image',
        ),
    ]
